# Generated by Django 4.2.5 on 2023-10-11 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('need_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IhtiyacForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100)),
                ('telefon', models.CharField(blank=True, max_length=100, null=True)),
                ('ihtiyaç_kategorisi', models.CharField(blank=True, choices=[('Temel İhtiyaçlar', 'A'), ('Sağlık Hizmetleri', 'B'), ('Psikososyal Destek', 'C'), ('Maddi Destek', 'D')], max_length=100, null=True)),
                ('adres', models.TextField()),
                ('email', models.PositiveIntegerField(default=0)),
                ('ihtiyac', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='need_api.ihtiyac')),
            ],
        ),
    ]
