# Generated by Django 4.2.5 on 2023-10-11 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
