# Generated by Django 4.2.5 on 2023-10-11 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('need_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Temel İhtiyaçlar', 'A'), ('Sağlık Hizmetleri', 'B'), ('Psikososyal Destek', 'C'), ('Maddi Destek', 'D')], max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('city', models.CharField(max_length=255)),
                ('ihtiyac', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='need_api.ihtiyac')),
            ],
        ),
    ]
